# Folosește imaginea oficială PostgreSQL ca bază
FROM postgres:latest

# Adaugă fișierele de configurare necesare sau execută comenzi suplimentare aici
# COPY custom-config.sql /docker-entrypoint-initdb.d/

# Specifică variabilele de mediu necesare
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase